// Generated by Wrangler on Sun May 26 2024 11:05:29 GMT-0600 (Mountain Daylight Time)
// by running `wrangler types`

interface Env {
	DISCORD_PUBLIC_KEY: "12082d47d2961296defd66b13cd8b05a231ea4c9588f912c83754c85e7292e94";
	DISCORD_APP_ID: "1134821767085555782";
}
